name: ChatControlPlugin
version: 1.0.2
main: me.kanuunankuulaspluginchat.chatSystem.ChatControlPlugin
api-version: 1.21
authors: [Kanuunankuula ( If_Master )]
website: https://www.spigotmc.org/resources/chatcontrolplugin.126110/
description: Advanced chat system with multiple channels and EssentialsChat integration
softdepend: [Vault, EssentialsChat]
folia-supported: true

commands:
  chat:
    description: Main chat command
    usage: /chat <subcommand>
    aliases: [ch, chatcontrol]
  cg_updatecheck:
    description: Check for plugin updates
    usage: /cg_updatecheck
    permission: chat.admin
    permission-message: You don't have permission to use this command.
  cg_update:
    description: Download and install plugin updates
    usage: /cg_update [confirm]
    permission: chat.admin
    permission-message: You don't have permission to use this command.


permissions:
  chat.forcejoin:
    description: Access to all chat channels
    default: op
  chat.updatefunction:
    description: Access to the update function
    default: op
  chat.admin:
    description: Access to all chat admin commands
    default: op
  chat.staff:
    description: Access to staff chat
    default: op
  chat.dev:
    description: Access to dev chat
    default: op
  chat.create:
    description: Create custom chat channels
    default: op
  chat.join:
    description: Join chat channels
    default: op
  chat.invite:
    description: Invite players to chat channels
    default: op
  chat.freeze:
    description: Freeze chat channels
    default: op
  chat.clear:
    description: Clear chat channels
    default: op
  chat.investigation:
    description: Investigation mode for monitoring
    default: op
  chat.channels.limit.<Amount>:
    description: Add here the amount you want the user to have for groups
    default: op
  chat.channels.unlimited:
    description: User will be able to generate Unlimited groups
    default: op
